using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MinimalApi.AutoDependencyInjection;


[Generator]
public class AutoDependencyInjectionSourceGenerator : IIncrementalGenerator
{
    private const string AttributeName = "AutoDependencyInjectionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var compilation = context.CompilationProvider;
        context.RegisterSourceOutput(compilation, (ctx, c) =>
        {
            var code = string.Empty;
            var usings = new HashSet<string>();

            for (var i = 0; i < c.SyntaxTrees.Count(); i++)
            {
                var tree = c.SyntaxTrees.ElementAt(i);
                var root = tree.GetCompilationUnitRoot();

                foreach (var member in root.Members)
                {
                    if (member is BaseNamespaceDeclarationSyntax namespaceDeclarationSyntax)
                    {
                        foreach (var item in namespaceDeclarationSyntax.Members)
                        {
                            SearchInMember(item, namespaceDeclarationSyntax.Name.ToString(), ref code, usings);
                        }
                    }
                }
            }

            var extensionCode = $$"""
                // <auto-generated/>

                using System;
                using Microsoft.Extensions.DependencyInjection;

                {{string.Join("\r\n", usings)}}

                namespace MinimalApi.AutoDependencyInjection
                {
                    [AttributeUsage(AttributeTargets.Class)]
                    public class {{AttributeName}} : Attribute
                    {
                        public ServiceLifetime Lifetime { get; private set; }

                        public Type InterfaceType { get; private set; }

                        public {{AttributeName}}(ServiceLifetime lifetime, Type interfaceType = null)
                        {
                            Lifetime = lifetime;
                            InterfaceType = interfaceType;
                        }
                    }

                    public static class ServiceCollectionAutoDependencyInjectionExtensions
                    {
                        public static void AutoRegisterAllServices(this IServiceCollection services)
                        {
                            {{code}}
                        }
                    }
                }
            """;

            ctx.AddSource(
                "MinimalApiExtensions.AutoDependencyInjection.g.cs",
                SourceText.From(extensionCode, Encoding.UTF8)
            );
        });
    }

    void SearchInMember(MemberDeclarationSyntax member, string currentPath, ref string code, HashSet<string> usings)
    {
        if (member is ClassDeclarationSyntax classSyntax)
        {
            foreach (var attributeList in classSyntax.AttributeLists)
            {
                foreach (var attribute in attributeList.Attributes)
                {
                    if (attribute.Name is IdentifierNameSyntax nameSyntax)
                    {
                        var attrName = nameSyntax.Identifier.Text;
                        if (attrName == AttributeName || $"{attrName}Attribute" == AttributeName)
                        {
                            foreach (var u in classSyntax.SyntaxTree.GetCompilationUnitRoot().Usings)
                            {
                                usings.Add(u.ToString());
                            }

                            var lifeTime = (attribute.ArgumentList!.Arguments.ElementAt(0).Expression as MemberAccessExpressionSyntax)!.Name.Identifier.Text;
                            var typeofSyntax = attribute.ArgumentList.Arguments.ElementAt(1).Expression as TypeOfExpressionSyntax;
                            var codeTemp = $"global::{currentPath}.{classSyntax.Identifier.Text}";
                            if (typeofSyntax != null)
                            {
                                codeTemp = typeofSyntax.Type.ToString() + "," + codeTemp;
                            }

                            code += $"services.Add{lifeTime}<{codeTemp}>();\r\n";
                        }
                    }
                }
            }

            foreach (var item in classSyntax.Members)
            {
                SearchInMember(item, $"{currentPath}.{classSyntax.Identifier.Text}", ref code, usings);
            }
        }
    }
}