<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="README.md" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
