<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" Condition="'$(TargetFramework)' == 'net9.0'"/>
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" Condition="'$(TargetFramework)' == 'net10.0'"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MinimalApi.Extensions.EFCore\MinimalApi.Extensions.EFCore.csproj" />
  </ItemGroup>

</Project>
