using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace MinimalApi.Extensions.SourceGeneration
{
    [Generator]
    public class AutoConfigOption : IIncrementalGenerator
    {
        private const string targetAttributeName = "MinimalApi.Extensions.Attributes.AutoConfigOptionAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 1. 筛选带有 AutoDependencyInjectionAttribute 的类
            var classDeclarations = context.FilterClassDeclarationsByAttribute(targetAttributeName);

            // 2. 收集需要的信息
            var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

            // 3. 生成代码
            context.RegisterSourceOutput(compilationAndClasses, (spc, source) =>
            {
                var (compilation, classes) = source;
                var injectCode = "";

                foreach (var classSymbol in classes)
                {
                    var attributeData = classSymbol.GetAttributes()
                   .First(ad => ad.AttributeClass?.ToDisplayString() == targetAttributeName);

                    var section = (string)attributeData.ConstructorArguments[0].Value!;

                    injectCode += $"services.Configure<{classSymbol.ToDisplayString()}>(configuration.GetSection(\"{section}\"));";
                }

                var code = $$"""
                    // <auto-generated/>

                    using System;
                    using Microsoft.Extensions.DependencyInjection;
                    using Microsoft.Extensions.DependencyInjection.Extensions;
                    using Microsoft.Extensions.Configuration;

                    namespace MinimalApi.Extensions
                    {
                        public static class ServiceCollectionAutoConfigOptionExtensions
                        {
                            public static IServiceCollection AutoConfigureOptions(this IServiceCollection services, IConfiguration configuration)
                            {
                                {{injectCode}}

                                return services;
                            }
                        }
                    }
                    """;

                spc.AddSource(
                    "MinimalApiExtensions.AutoConfigOption.g.cs",
                    SourceText.From(code, Encoding.UTF8)
                );
            });
        }
    }
}
