using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using MinimalApi.Extensions.Abstractions.Attributes;

namespace MinimalApi.Extensions.SourceGeneration;


[Generator]
public class AutoDependencyInjection : IIncrementalGenerator
{
    private readonly string attributeName = nameof(AutoDependencyInjectionAttribute);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var compilation = context.CompilationProvider;
        context.RegisterSourceOutput(compilation, (ctx, c) =>
        {
            var code = string.Empty;

            for (var i = 0; i < c.SyntaxTrees.Count(); i++)
            {
                var tree = c.SyntaxTrees.ElementAt(i);
                var root = tree.GetCompilationUnitRoot();

                // 获取语义模型
                var semanticModel = c.GetSemanticModel(tree)!;
                var classDeclarations = root.DescendantNodes().OfType<ClassDeclarationSyntax>();

                foreach (var classDeclaration in classDeclarations)
                {
                    AppendCode( semanticModel, classDeclaration,ref code);
                }
            }

            var extensionCode = $$"""
                // <auto-generated/>

                using System;
                using Microsoft.Extensions.DependencyInjection;

                namespace MinimalApi.Extensions
                {
                    public static class ServiceCollectionAutoDependencyInjectionExtensions
                    {
                        public static void AutoRegisterAllServices(this IServiceCollection services)
                        {
                            {{code}}
                        }
                    }
                }
            """;

            ctx.AddSource(
                "MinimalApiExtensions.AutoDependencyInjection.g.cs",
                SourceText.From(extensionCode, Encoding.UTF8)
            );
        });
    }

    void AppendCode(SemanticModel semanticModel, ClassDeclarationSyntax classDeclarationSyntax, ref string code)
    {
        foreach (var attributeList in classDeclarationSyntax.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                if (attribute.Name is IdentifierNameSyntax nameSyntax)
                {
                    var attrName = nameSyntax.Identifier.Text;
                    if (attrName == attributeName || $"{attrName}Attribute" == attributeName)
                    {
                        var lifeTime = (attribute.ArgumentList!.Arguments.ElementAt(0).Expression as MemberAccessExpressionSyntax)!.Name.Identifier.Text;
                        var codeTemp = semanticModel.GetDeclaredSymbol(classDeclarationSyntax)!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                        if (attribute.ArgumentList.Arguments.ElementAt(1).Expression is TypeOfExpressionSyntax typeofSyntax)
                        {
                            var typeSymbol = semanticModel.GetTypeInfo(typeofSyntax.Type).Type;
                            if (typeSymbol != null)
                            {
                                codeTemp = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "," + codeTemp;
                            }
                            else
                            {
                                codeTemp = typeofSyntax.Type.ToString();
                            }
                        }

                        code += $"services.Add{lifeTime}<{codeTemp}>();\r\n";
                    }
                }
            }
        }
    }
}