using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace MinimalApi.Extensions.SourceGeneration
{
    [Generator]
    public class AutoDependencyInjection : IIncrementalGenerator
    {
        private const string targetAttributeName = "MinimalApi.Extensions.Attributes.AutoDependencyInjectionAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 1. 筛选带有 AutoDependencyInjectionAttribute 的类
            var classDeclarations = context.FilterClassDeclarationsByAttribute(targetAttributeName);

            // 2. 收集需要的信息
            var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

            // 3. 生成代码
            context.RegisterSourceOutput(compilationAndClasses, (spc, source) =>
            {
                var (compilation, classes) = source;
                var injectCode = "";

                foreach (var classSymbol in classes)
                {
                    var attributeData = classSymbol.GetAttributes()
                   .First(ad => ad.AttributeClass?.ToDisplayString() == targetAttributeName);

                    var lifetime = (int)attributeData.ConstructorArguments[0].Value!;
                    var interfaceTypeNames = GetNamedArgumentArrayString(attributeData, "InterfaceTypes");
                    var key = GetNamedArgumentValue<string?>(attributeData, "Key", null);
                    var useTry = GetNamedArgumentValue<bool>(attributeData, "UseTry", false);

                    GenerateCode(classSymbol, lifetime, interfaceTypeNames, key, useTry, ref injectCode);
                }

                var code = $$"""
                    // <auto-generated/>

                    using System;
                    using Microsoft.Extensions.DependencyInjection;
                    using Microsoft.Extensions.DependencyInjection.Extensions;

                    namespace MinimalApi.Extensions
                    {
                        public static class ServiceCollectionAutoDependencyInjectionExtensions
                        {
                            public static IServiceCollection AutoRegisterServices(this IServiceCollection services)
                            {
                                {{injectCode}}

                                return services;
                            }
                        }
                    }
                    """;

                spc.AddSource(
                    "MinimalApiExtensions.AutoDependencyInjection.g.cs",
                    SourceText.From(code, Encoding.UTF8)
                );
            });
        }

        private void GenerateCode(ISymbol classSymbol, int lifetime, IEnumerable<string> interfaceTypeNames, string? key, bool useTry, ref string injectCode)
        {
            var className = classSymbol.ToDisplayString();
            var functionName = "Add";

            if (useTry)
            {
                functionName = "Try" + functionName;
            }

            if (key is not null)
            {
                functionName += "Keyed";
            }

            functionName += lifetime switch {
                0 => "Singleton",
                1 => "Scoped",
                2 => "Transient",
                _ => "Scoped"
            };

            if (interfaceTypeNames != null && interfaceTypeNames.Any())
            {
                foreach (var interfaceTypeName in interfaceTypeNames)
                {
                    injectCode += $"services.{functionName}<{interfaceTypeName}, {className}>({key ?? ""});\r\n";
                }
            }
            else
            {
                injectCode += $"services.{functionName}<{className}>(\"{key ?? ""}\");\r\n";
            }
        }

        private static T GetNamedArgumentValue<T>(AttributeData attributeData, string argumentName, T defaultValue)
        {
            var namedArg = attributeData.NamedArguments.FirstOrDefault(na => na.Key == argumentName);
            if (namedArg.Key == null) return defaultValue;

            return namedArg.Value.Value is T value ? value : defaultValue;
        }

        private static IEnumerable<string> GetNamedArgumentArrayString(AttributeData attributeData, string argumentName)
        {
            var namedArg = attributeData.NamedArguments.FirstOrDefault(na => na.Key == argumentName);
            if (namedArg.Key == null) return [];

            return namedArg.Value.Values.Where(x=>x.Value != null).Select(x=>x.Value!.ToString());
        }
    }
}
