using System.Diagnostics;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using MinimalApi.Extensions.Attributes;

namespace MinimalApi.Extensions.SourceGeneration;

[Generator]
public class AutoDependencyInjection : IIncrementalGenerator
{
    private readonly string attributeName = nameof(AutoDependencyInjectionAttribute);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var compilationProvider = context.CompilationProvider;
        context.RegisterSourceOutput(
            compilationProvider,
            (ctx, compilation) =>
            {
                var code = string.Empty;
                AppendCode(compilation, ref code);

                var extensionCode = $$"""
                    // <auto-generated/>

                    using System;
                    using Microsoft.Extensions.DependencyInjection;

                    namespace MinimalApi.Extensions
                    {
                        public static class ServiceCollectionAutoDependencyInjectionExtensions
                        {
                            public static void AutoRegisterAllServices(this IServiceCollection services)
                            {
                                {{code}}
                            }
                        }
                    }
                """;

                ctx.AddSource(
                    "MinimalApiExtensions.AutoDependencyInjection.g.cs",
                    SourceText.From(extensionCode, Encoding.UTF8)
                );
            }
        );
    }

    void AppendCode(Compilation compilation, ref string code)
    {
        foreach (var syntaxTree in compilation.SyntaxTrees)
        {
            // 获取语义模型
            var semanticModel = compilation.GetSemanticModel(syntaxTree)!;

            foreach (
                var classDeclaration in syntaxTree
                    .GetCompilationUnitRoot()
                    .DescendantNodes()
                    .OfType<ClassDeclarationSyntax>()
            )
            {
                AppendCode(semanticModel, classDeclaration, ref code);
            }
        }
    }

    void AppendCode(
        SemanticModel semanticModel,
        ClassDeclarationSyntax classDeclarationSyntax,
        ref string code
    )
    {
        foreach (var attributeList in classDeclarationSyntax.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                if (attribute.Name is IdentifierNameSyntax nameSyntax)
                {
                    var attrName = nameSyntax.Identifier.Text;
                    if (attrName == attributeName || $"{attrName}Attribute" == attributeName)
                    {
                        var lifeTime = (
                            attribute.ArgumentList!.Arguments.ElementAt(0).Expression
                            as MemberAccessExpressionSyntax
                        )!
                            .Name
                            .Identifier
                            .Text;
                        var codeTemp = semanticModel
                            .GetDeclaredSymbol(classDeclarationSyntax)!
                            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                        if (
                            attribute.ArgumentList.Arguments.ElementAt(1).Expression
                            is TypeOfExpressionSyntax typeofSyntax
                        )
                        {
                            var typeSymbol = semanticModel.GetTypeInfo(typeofSyntax.Type).Type;
                            if (typeSymbol != null)
                            {
                                codeTemp =
                                    typeSymbol.ToDisplayString(
                                        SymbolDisplayFormat.FullyQualifiedFormat
                                    )
                                    + ","
                                    + codeTemp;
                            }
                            else
                            {
                                codeTemp = typeofSyntax.Type.ToString();
                            }
                        }

                        Debugger.Launch();

                        if (attribute.ArgumentList!.Arguments.Count > 2)
                        {
                            var key = (
                                attribute.ArgumentList!.Arguments.ElementAt(2).Expression
                                as LiteralExpressionSyntax
                            );
                        }

                        code += $"services.Add{lifeTime}<{codeTemp}>();\r\n";
                    }
                }
            }
        }
    }
}
