<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
	  <PackageReference Include="Scalar.AspNetCore" Version="2.1.17" />
	</ItemGroup>

</Project>
