<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="True" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="EFCore.NamingConventions" Version="9.0.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	</ItemGroup>
</Project>
